"""changes in status model

Revision ID: 451d7c3c5d48
Revises: a6b75670980c
Create Date: 2020-11-17 12:40:50.384800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451d7c3c5d48'
down_revision = 'a6b75670980c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status_sm_comments', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('status_sm_likes', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('status_sm_shares', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'status_sm_shares')
    op.drop_column('statuses', 'status_sm_likes')
    op.drop_column('statuses', 'status_sm_comments')
    # ### end Alembic commands ###
