"""status model changed, id column added

Revision ID: 5f71129cb779
Revises: 66f23b367830
Create Date: 2020-11-18 13:35:04.176771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f71129cb779'
down_revision = '66f23b367830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status_sm_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'status_sm_id')
    # ### end Alembic commands ###
