"""status model changed

Revision ID: 66f23b367830
Revises: 451d7c3c5d48
Create Date: 2020-11-18 13:31:15.460086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66f23b367830'
down_revision = '451d7c3c5d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('club_id', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('is_app_status', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('is_player_status', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('is_sm_status', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_column('statuses', 'status_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('statuses', 'player_id')
    op.drop_column('statuses', 'is_sm_status')
    op.drop_column('statuses', 'is_player_status')
    op.drop_column('statuses', 'is_app_status')
    op.drop_column('statuses', 'club_id')
    # ### end Alembic commands ###
