"""rating model changed

Revision ID: 74ba3c5d1db3
Revises: b762b817d810
Create Date: 2020-12-10 11:25:56.848411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ba3c5d1db3'
down_revision = 'b762b817d810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('review', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'review')
    # ### end Alembic commands ###
