"""chat functionality started

Revision ID: 752f5695ebe1
Revises: c2856292cdb8
Create Date: 2021-01-21 12:16:41.811413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752f5695ebe1'
down_revision = 'c2856292cdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_participants',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('chat_initiater_id', sa.Integer(), nullable=True),
    sa.Column('chat_initiated_with_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('message',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('msg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat_participants')
    # ### end Alembic commands ###
