"""comment model changed

Revision ID: 7923fd15ca83
Revises: 4fb062a055a2
Create Date: 2020-11-26 11:56:58.940414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7923fd15ca83'
down_revision = '4fb062a055a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'rating')
    # ### end Alembic commands ###
