"""club model changed

Revision ID: 793fe44c3506
Revises: aa172411566c
Create Date: 2020-12-08 15:58:09.546967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793fe44c3506'
down_revision = 'aa172411566c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('club_media', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'club_media')
    # ### end Alembic commands ###
