"""message model changed

Revision ID: 8ef65141a907
Revises: 6709ca2c9214
Create Date: 2021-01-21 13:22:11.751522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef65141a907'
down_revision = '6709ca2c9214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_forwarded', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_forwarded')
    # ### end Alembic commands ###
