"""like model added

Revision ID: 95a07adca5e9
Revises: 5f71129cb779
Create Date: 2020-11-19 13:00:50.936393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a07adca5e9'
down_revision = '5f71129cb779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('is_status', sa.Integer(), nullable=True),
    sa.Column('is_player', sa.Integer(), nullable=True),
    sa.Column('is_club', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
