"""clubs model added

Revision ID: a6b75670980c
Revises: a651a9878cab
Create Date: 2020-11-07 16:14:08.253727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b75670980c'
down_revision = 'a651a9878cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('club_country', sa.String(length=100), nullable=False),
    sa.Column('club_union_federation', sa.String(length=100), nullable=False),
    sa.Column('club_profile_pic', sa.Text(), nullable=True),
    sa.Column('club_cover_pic', sa.Text(), nullable=True),
    sa.Column('web_link', sa.Text(), nullable=True),
    sa.Column('fb_link', sa.Text(), nullable=True),
    sa.Column('twitter_link', sa.Text(), nullable=True),
    sa.Column('instagram_link', sa.Text(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_address', sa.String(length=100), nullable=True),
    sa.Column('holes_9_or_18', sa.Integer(), nullable=True),
    sa.Column('public_or_private', sa.String(length=50), nullable=True),
    sa.Column('fb_followers', sa.Integer(), nullable=True),
    sa.Column('twitter_followers', sa.Integer(), nullable=True),
    sa.Column('insta_followers', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('club_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubs')
    # ### end Alembic commands ###
