"""rating model removed

Revision ID: aa172411566c
Revises: 7923fd15ca83
Create Date: 2020-11-26 11:58:50.357392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa172411566c'
down_revision = '7923fd15ca83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('rating_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('is_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_player', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_club', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('player_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('club_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rating_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
