"""rating model changed

Revision ID: b762b817d810
Revises: e727a660a051
Create Date: 2020-12-10 10:29:04.349473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b762b817d810'
down_revision = 'e727a660a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('club_id', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('player_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'player_id')
    op.drop_column('ratings', 'club_id')
    # ### end Alembic commands ###
