"""player model created

Revision ID: c78b5bd64fce
Revises: 74ba3c5d1db3
Create Date: 2020-12-16 22:27:47.217033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78b5bd64fce'
down_revision = '74ba3c5d1db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('player_profile_pic', sa.Text(), nullable=True),
    sa.Column('player_cover_pic', sa.Text(), nullable=True),
    sa.Column('web_link', sa.Text(), nullable=True),
    sa.Column('fb_link', sa.Text(), nullable=True),
    sa.Column('twitter_link', sa.Text(), nullable=True),
    sa.Column('instagram_link', sa.Text(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_address', sa.String(length=100), nullable=True),
    sa.Column('fb_followers', sa.Integer(), nullable=True),
    sa.Column('twitter_followers', sa.Integer(), nullable=True),
    sa.Column('insta_followers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
