"""is publised column added

Revision ID: de6ee4f838e0
Revises: c78b5bd64fce
Create Date: 2020-12-19 23:29:43.527861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6ee4f838e0'
down_revision = 'c78b5bd64fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('is_published', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'is_published')
    # ### end Alembic commands ###
