"""like model changed

Revision ID: fe3aed129847
Revises: 95a07adca5e9
Create Date: 2020-11-19 13:04:01.028643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3aed129847'
down_revision = '95a07adca5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('club_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('status_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'status_id')
    op.drop_column('likes', 'player_id')
    op.drop_column('likes', 'club_id')
    # ### end Alembic commands ###
